import { Inter } from "next/font/google";
import "./globals.css";
import SideNav from "./Component/SideNav/SideNav";
import Category from "./Component/Category/Category";
import Topnav from "./Component/Topnav/Topnav";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Dua & Ruqiya",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body className={inter.className}>

        <div className=" block lg:flex lg:flex-row-reverse  p-5 gap-6 bg-base-300">

          <div className="w-full ">
            <Topnav></Topnav>
            <div className=" w-full  lg:flex   bg-base-300">



              <Category></Category>



              <div>{children}</div>



            </div>
          </div>
          <div >
            <SideNav></SideNav>
          </div>
        </div>
      </body>
    </html>
  );
}
